[workspace]
members = ["crates/protocol", "crates/commitments", "crates/credentials", "crates/settlement", "crates/zcash-adapter", "matcher"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Maheshsiddu29/ZWA-Protocol"

[workspace.dependencies]
zwa-protocol = { path = "crates/protocol", version = "0.1.0" }
zwa-credentials = { path = "crates/credentials", version = "0.1.0" }
zwa-commitments = { path = "crates/commitments", version = "0.1.0" }

ark-bn254 = { version = "0.5.0", default-features = false, features = ["scalar_field"] }
ark-ff = { version = "0.5.0", default-features = false }
ark-ec = { version = "0.5.0", default-features = false }
ark-groth16 = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
light-poseidon = "0.4.0"
serde_json = "1.0.151"
thiserror = "2.0.20"
sha2 = "0.10.8"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
